#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Ingo Ruhnke <grumbel@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate deterministic synthetic JPEG/PNG fixtures for pixel benches.

Uses the ``vips`` CLI so the flake only needs the vips package.
Output layout::

  out/
    synthetic/
      jpeg/synth_{w}x{h}_q90.jpg
      png/synth_{w}x{h}.png
    manifest.json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

SIZES = [
    (800, 600),
    (1920, 1080),
    (3840, 2160),
    (7680, 4320),
]

JPEG_Q = 90


def run(cmd: list[str]) -> None:
    subprocess.check_call(cmd)


def make_pattern(w: int, h: int, out_png: Path) -> None:
    """Deterministic greyscale ramp (stable across vips versions for fixed WxH)."""
    run(["vips", "grey", str(out_png), str(w), str(h), "--uchar"])


def encode_jpeg(png: Path, jpg: Path, quality: int) -> None:
    run(
        [
            "vips",
            "jpegsave",
            str(png),
            str(jpg),
            "--Q",
            str(quality),
            "--optimize-coding",
            "--strip",
        ]
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, required=True, help="output root directory")
    args = ap.parse_args()
    root: Path = args.out
    jpeg_dir = root / "synthetic" / "jpeg"
    png_dir = root / "synthetic" / "png"
    jpeg_dir.mkdir(parents=True, exist_ok=True)
    png_dir.mkdir(parents=True, exist_ok=True)

    entries: list[dict] = []
    for w, h in SIZES:
        stem = f"synth_{w}x{h}"
        png_path = png_dir / f"{stem}.png"
        jpg_path = jpeg_dir / f"{stem}_q{JPEG_Q}.jpg"
        make_pattern(w, h, png_path)
        encode_jpeg(png_path, jpg_path, JPEG_Q)
        mpix = (w * h) / 1e6
        for path, codec in ((png_path, "png"), (jpg_path, "jpeg")):
            rel = str(path.relative_to(root))
            entries.append(
                {
                    "id": f"{stem}_{codec}",
                    "path": rel,
                    "class": "synthetic",
                    "codec": codec,
                    "width": w,
                    "height": h,
                    "mpix": round(mpix, 3),
                    "license": "GPL-3.0-or-later",
                    "notes": "generated by generators/gen_synthetic.py",
                }
            )
        print(f"wrote {jpg_path.name} ({mpix:.2f} MP)", file=sys.stderr)

    manifest = {
        "schema": 1,
        "generator": "gen_synthetic.py",
        "entries": entries,
    }
    man_path = root / "manifest.json"
    man_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"manifest entries={len(entries)} -> {man_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
